export enum Icons {
  "Café da manhã incluso" = "fa-solid fa-mug-hot",
  Estacionamento = "fa-solid fa-car-side",
  Piscina = "fa-solid fa-person-swimming",
  "Recepção 24 horas" = "fa-solid fa-bell-concierge",
  Restaurante = "fa-solid fa-utensils",
  Spa = "fa-solid fa-spa",
  "Wi-Fi grátis" = "fa-solid fa-wifi",
  Academia = "fa-solid fa-dumbbell",
  "Pet friendly" = "fa-solid fa-paw",
  "Serviço de quarto" = "fa-solid fa-broom",
  Bar = "fa-solid fa-martini-glass",

  arrowLeft = "fa-solid fa-angle-left",
  bed = "fa-solid fa-bed",
  calendar = "fa-regular fa-calendar",
  calendarCheck = "fa-regular fa-calendar-check",
  checkin = "fa-regular fa-calendar-check",
  checkout = "fa-regular fa-calendar-xmark",
  children = "fa-solid fa-children",
  close = "fa fa-close",
  details = "fa-solid fa-angles-right",
  findLocation = "fa-solid fa-location",
  home = 'fa-solid fa-home',
  hotel = "fa-solid fa-hotel",
  location = "fa-solid fa-location-dot",
  minus = "fa fa-minus",
  money = "fa-solid fa-money-bill",
  note = "fa-solid fa-clipboard",
  plus = "fa fa-plus",
  policy = "fa-solid fa-building-shield",
  sad = "fa-regular fa-face-frown",
  search = 'fa-solid fa-search',
  sort = "fa-solid fa-arrow-down-wide-short",
  star = "fa-solid fa-star",
  suitcase = "fa-solid fa-suitcase-rolling",
  user = "fa-solid fa-user",
  users = "fa-solid fa-users",
}

export const icons = Icons;
