name: CI

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install dependencies
        run: |
          npm install -g @vue/cli yarn
          yarn install

      - name: Build Application
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone --depth 1 --branch gh-pages https://github.com/andre-menezes/o-nomade.git gh-pages

          rm -rf gh-pages/*

          cp -r dist/* gh-pages/

          cd gh-pages
          git add .
          git commit -m "Deploy de aplicação Vue 3 - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages
