name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      actions: 'write'
      checks: 'write'
      deployments: 'write'
    
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js e Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Instalar dependências e construir
        run: |
          npm install -g @vue/cli yarn
          yarn install
          yarn build

      - name: Configurar Pages
        uses: actions/configure-pages@v3

      - name: Enviar artefato
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'

      - name: Fazer deploy no GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
